const NOTES_SELECTED = 'NOTES_SELECTED';
const NOTES_ADD = 'NOTES_ADD';
const NOTES_CHANGE = 'NOTES_CHANGE';
const NOTES_SUBMIT = 'NOTES_SUBMIT';
const NOTES_DELETE = 'NOTES_DELETE';
const PREVIEW_REFRESH = 'PREVIEW_REFRESH';

export { NOTES_SELECTED, NOTES_ADD, NOTES_CHANGE, NOTES_SUBMIT, NOTES_DELETE, PREVIEW_REFRESH };